version: "3"
services:
  nginx:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    ports:
      - "8080:80"
    links:
        - database
    networks:
      - internal
    volumes:
      - .:/var/www/html/
      - ./logs/nginx:/var/log/nginx/
  php:
    depends_on:
      - database
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    networks:
      - internal
    volumes:
      - .:/var/www/html/
      - ./logs/php.log:/var/log/fpm-php.www.log
    links:
      - database
    ports:
      - "9000:9000"
    environment:
      - COMPOSER_MEMORY_LIMIT=-1
 #   command: /bin/bash -c "cp .env.example .env &&
 #     composer install --optimize-autoloader --no-interaction --ansi
 #       && php artisan migrate --seed"

  database:
    build:
      context: .
      dockerfile: docker/mysql8/Dockerfile
    restart: "always"
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: booking
      MYSQL_USER: cubicfoxmysql
      MYSQL_PASSWORD: cubicfoxmysql
      TZ: Europe/Budapest
    networks:
        - internal
networks:
  internal:
    driver: bridge
volumes:
  db_data:
